spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

app:
  jwt:
    secret: my-local-dev-secret-key-12345678901234567890
    expiration-ms: 86400000